window.TRAVEL_CONFIG={
  DEFAULT_COUNTRY:'IN',
  API_URL:'https://script.google.com/macros/s/AKfycbxgwRnieoT7LFA0FWyd-PKvsr3nvElDdM1eyUfqvuUGZbxH29HUzwrScxVTXh1fEKNYDw/exec',
  ADMIN_URL:'https://script.google.com/macros/s/AKfycbxgwRnieoT7LFA0FWyd-PKvsr3nvElDdM1eyUfqvuUGZbxH29HUzwrScxVTXh1fEKNYDw/exec',
  REST_COUNTRIES_BASE:'https://restcountries.com/v3.1',
  OPEN_METEO_FORECAST:'https://api.open-meteo.com/v1/forecast',
  FX_RATE_BASE:'https://api.frankfurter.dev/v2/rate',
  DEFAULT_PROFILE:{passportCountry:'IN',homeCurrency:'INR',travelStyle:'Mid-range',interests:['Culture','Nature','Food']}
};
